version: '3.7'

services: 
    web:
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
        environment: 
            - SECRET_KEY=6x3a8acht$$-r#4wu@55i%(d8yua6sr$$p%r^jik+av0mh*1*d!(
            - DEBUG=1
        volumes: 
            - .:/code
        ports: 
            - 8000:8000
        depends_on: 
            - db

    db:
        image: postgres:11
        volumes: 
            - postgres_data:/var/lib/postgresql/data/

volumes: 
    postgres_data: